@startuml Question Service

entity Question {
  + questionId : number
  + title : string
  + description : string
  + complexity : string
  + categories : Array<string>
}

entity EditQuestion {
  + title : string
  + description : string
  + complexity : string
  + categories : Array<string>
}

entity Pagination {
  + pagination : number = 1
  + pageSize : number = 10
}

interface IQuestionServiceAPI {
  + GET /
  + POST /create [createQuestion: EditQuestion]
  + POST /all [pagination: Pagination]
  + GET /{id}
  + POST /{id}/update [updateQuestion: EditQuestion]
  + POST /{id}/delete
}

note right of IQuestionServiceAPI
  - GET /: Check service status
  - POST /create: Create a new question
  - POST /all: Retrieve all questions with pagination
  - GET /{id}: Retrieve a specific question by ID
  - POST /{id}/update: Update a specific question by ID
  - POST /{id}/delete: Delete a specific question by ID
end note

class QuestionService {
}

entity QuestionDatabase {
  + questions: Array<Question>
}

QuestionService ..|> IQuestionServiceAPI : implements
QuestionService --> QuestionDatabase : interacts with

@enduml