gantt
    dateFormat  YYYY-MM-DD
    title CS3219 Project Timeline
    axisFormat %Y-%m-%d
    
    section Sprint 1
    Set up database                :done, s1t1, 2024-09-17, 2024-09-23
    Display question list          :done, s1t2, 2024-09-17, 2024-09-23
    Display question desc.         :done, s1t3, 2024-09-17, 2024-09-23
    Login/Logout routes            :done, s1t4, 2024-09-17, 2024-09-23
    Homepage after login           :done, s1t5, 2024-09-17, 2024-09-23
    Link question frontend         :done, s1t6, 2024-09-17, 2024-09-23
    K8s cloud setup                :done, s1t7, 2024-09-17, 2024-09-23

    section Sprint 2
    User service                :done, s1t7, 2024-09-24, 2024-09-30
    Question filtering           :done, s3t1, 2024-09-24, 2024-09-30
    Question sorting            :done, s3t2, 2024-09-24, 2024-09-30
    
    section Sprint 3
    Hot reloading              :done, s3t3, 2024-10-01, 2024-10-07
    Update user service        :done, s3t4, 2024-10-01, 2024-10-07
    Login UI                   :done, s3t5, 2024-10-01, 2024-10-07

    section Sprint 4
    Admin question UI          :done, s4t1, 2024-10-08, 2024-10-14
    Setup RabbitMQ            :done, s4t2, 2024-10-08, 2024-10-14
    Continuous deployment            :done, s4t3, 2024-10-08, 2024-10-14

    section Sprint 5
    Matching service          :done, s5t2, 2024-10-15, 2024-10-21
    Loading page             :done, s5t3, 2024-10-15, 2024-10-21
    Frontend-RabbitMQ        :done, s5t4, 2024-10-15, 2024-10-21

    section Sprint 6
    API Gateway CRUD         :done, s6t1, 2024-10-22, 2024-10-28
    Collaboration page         :done, s6t1, 2024-10-22, 2024-10-28
    
    section Sprint 7
    Audio service            :done, s7t1, 2024-10-29, 2024-11-04
    Code execution         :done, s7t2, 2024-10-29, 2024-11-04
    User profile          :done, s7t3, 2024-10-29, 2024-11-04
    OAuth                 :done, s7t4, 2024-10-29, 2024-11-04
    Collaboration service        :done, s7t5, 2024-10-29, 2024-11-04
    Cloud deployment     :done, s7t6, 2024-10-29, 2024-11-04