export enum Category {
    STRINGS = 'STRINGS',
    ARRAYS = 'ARRAYS',
    DATA_STRUCTURES = 'DATA STRUCTURES',
    ALGORITHMS = 'ALGORITHMS',
    BIT_MANIPULATION = 'BIT MANIPULATION',
    RECURSION = 'RECURSION',
    DATABASES = 'DATABASES',
    BRAINTEASER = 'BRAINTEASER',
}
