apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-question
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-question
  template:
    metadata:
      labels:
        app: mongo-question
    spec:
      containers:
      - name: mongo-question
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-question-secret
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-user-secret
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-question-pvc
