apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: gcr.io/peerprep-438713/matching-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: FRONTEND_URL 
          value: "http://34.101.228.125"
        - name: USER_SERVICE_URL
          value: "http://user-service:3001"
