export const CategoriesOption = [
  { label: "Array", value: "Array" },
  { label: "String", value: "String" },
  { label: "Hash Table", value: "Hash Table" },
  { label: "Dynamic Programming", value: "Dynamic Programming" },
  { label: "Math", value: "Math" },
  { label: "Sorting", value: "Sorting" },
  { label: "Greedy", value: "Greedy" },
  { label: "Depth-First Search", value: "Depth-First Search" },
  { label: "Database", value: "Database" },
  { label: "Binary Search", value: "Binary Search" },
  { label: "Matrix", value: "Matrix" },
  { label: "Breadth-First Search", value: "Breadth-First Search" },
  { label: "Tree", value: "Tree" },
  { label: "Bit Manipulation", value: "Bit Manipulation" },
  { label: "Two Pointers", value: "Two Pointers" },
  { label: "Binary Tree", value: "Binary Tree" },
  { label: "Heap (Priority Queue)", value: "Heap (Priority Queue)" },
  { label: "Prefix Sum", value: "Prefix Sum" },
  { label: "Simulation", value: "Simulation" },
  { label: "Stack", value: "Stack" },
  { label: "Counting", value: "Counting" },
  { label: "Graph", value: "Graph" },
  { label: "Sliding Window", value: "Sliding Window" },
  { label: "Design", value: "Design" },
  { label: "Backtracking", value: "Backtracking" },
  { label: "Enumeration", value: "Enumeration" },
  { label: "Union Find", value: "Union Find" },
  { label: "Linked List", value: "Linked List" },
  { label: "Ordered Set", value: "Ordered Set" },
  { label: "Monotonic Stack", value: "Monotonic Stack" },
  { label: "Number Theory", value: "Number Theory" },
  { label: "Trie", value: "Trie" },
  { label: "Segment Tree", value: "Segment Tree" },
  { label: "Bitmask", value: "Bitmask" },
  { label: "Divide and Conquer", value: "Divide and Conquer" },
  { label: "Queue", value: "Queue" },
  { label: "Recursion", value: "Recursion" },
  { label: "Binary Search Tree", value: "Binary Search Tree" },
  { label: "Combinatorics", value: "Combinatorics" },
  { label: "Binary Indexed Tree", value: "Binary Indexed Tree" },
  { label: "Hash Function", value: "Hash Function" },
  { label: "Geometry", value: "Geometry" },
  { label: "Memoization", value: "Memoization" },
  { label: "String Matching", value: "String Matching" },
  { label: "Topological Sort", value: "Topological Sort" },
  { label: "Rolling Hash", value: "Rolling Hash" },
  { label: "Shortest Path", value: "Shortest Path" },
  { label: "Game Theory", value: "Game Theory" },
  { label: "Interactive", value: "Interactive" },
  { label: "Data Stream", value: "Data Stream" },
  { label: "Monotonic Queue", value: "Monotonic Queue" },
  { label: "Brainteaser", value: "Brainteaser" },
  { label: "Randomized", value: "Randomized" },
  { label: "Merge Sort", value: "Merge Sort" },
  { label: "Doubly-Linked List", value: "Doubly-Linked List" },
  { label: "Counting Sort", value: "Counting Sort" },
  { label: "Iterator", value: "Iterator" },
  { label: "Concurrency", value: "Concurrency" },
  { label: "Probability and Statistics", value: "Probability and Statistics" },
  { label: "Quickselect", value: "Quickselect" },
  { label: "Suffix Array", value: "Suffix Array" },
  { label: "Bucket Sort", value: "Bucket Sort" },
  { label: "Minimum Spanning Tree", value: "Minimum Spanning Tree" },
  { label: "Shell", value: "Shell" },
  { label: "Line Sweep", value: "Line Sweep" },
  { label: "Reservoir Sampling", value: "Reservoir Sampling" },
  {
    label: "Strongly Connected Component",
    value: "Strongly Connected Component",
  },
  { label: "Eulerian Circuit", value: "Eulerian Circuit" },
  { label: "Radix Sort", value: "Radix Sort" },
  { label: "Rejection Sampling", value: "Rejection Sampling" },
  { label: "Biconnected Component", value: "Biconnected Component" },
];

export const DifficultyOption = [
  {
    label: "Easy",
    value: "Easy",
  },
  {
    label: "Medium",
    value: "Medium",
  },
  {
    label: "Hard",
    value: "Hard",
  },
];

export const OrderOption = [
  {
    label: "Newest",
    value: "Newest",
  },
  {
    label: "Oldest",
    value: "Oldest",
  },
];
