apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: collab-service-hpa
  namespace: peerprep-collab-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collab-service
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70