apiVersion: v1
kind: Service
metadata:
  name: collab-service
  namespace: peerprep-collab-service
spec:
  selector:
    app: collab-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP  # Use 'NodePort' if you want to expose the service externally