import { Question } from '@/types/question-types';

export const dummyData: Question[] = [
  {
    id: 1,
    attempted: true,
    title: 'Basic Arrays',
    difficulty: 'Easy',
    topic: ['Arrays', 'Basic'],
  },
  {
    id: 2,
    attempted: false,
    title: 'Sorting Algorithms',
    difficulty: 'Medium',
    topic: ['Algorithms', 'Sorting'],
  },
  {
    id: 3,
    attempted: true,
    title: 'Graph Traversal',
    difficulty: 'Hard',
    topic: ['Graphs', 'DFS', 'BFS'],
  },
  {
    id: 4,
    attempted: false,
    title: 'Dynamic Programming',
    difficulty: 'Hard',
    topic: ['Dynamic Programming'],
  },
  {
    id: 5,
    attempted: true,
    title: 'Binary Search Trees',
    difficulty: 'Medium',
    topic: ['Trees', 'Binary Search'],
  },
  {
    id: 6,
    attempted: false,
    title: 'Recursion Basics',
    difficulty: 'Easy',
    topic: ['Recursion'],
  },
  {
    id: 7,
    attempted: true,
    title: 'Hash Tables',
    difficulty: 'Easy',
    topic: ['Data Structures', 'Hashing'],
  },
  {
    id: 8,
    attempted: false,
    title: 'Graph Algorithms',
    difficulty: 'Medium',
    topic: ['Graphs', 'Shortest Path'],
  },
  {
    id: 9,
    attempted: true,
    title: 'Object-Oriented Programming',
    difficulty: 'Medium',
    topic: ['OOP', 'Classes', 'Inheritance'],
  },
  {
    id: 10,
    attempted: false,
    title: 'Concurrency Basics',
    difficulty: 'Hard',
    topic: ['Concurrency', 'Multithreading'],
  },
  {
    id: 11,
    attempted: true,
    title: 'Machine Learning Introduction',
    difficulty: 'Medium',
    topic: ['Machine Learning', 'Algorithms'],
  },
];
