import { Question } from '@/types/question-types';

export const dummyData: Question[] = [
  {
    id: 1,
    attempted: true,
    title: 'Basic Arrays',
    difficulty: 'Easy',
    topic: ['Arrays', 'Basic'],
  },
  {
    id: 2,
    attempted: false,
    title: 'Sorting Algorithms',
    difficulty: 'Medium',
    topic: ['Algorithms', 'Sorting'],
  },
  {
    id: 3,
    attempted: true,
    title: 'Graph Traversal',
    difficulty: 'Hard',
    topic: ['Graphs', 'DFS', 'BFS'],
  },
  {
    id: 4,
    attempted: false,
    title: 'Dynamic Programming',
    difficulty: 'Hard',
    topic: ['Dynamic Programming'],
  },
  {
    id: 5,
    attempted: true,
    title: 'Binary Search Trees',
    difficulty: 'Medium',
    topic: ['Trees', 'Binary Search'],
  },
  {
    id: 6,
    attempted: false,
    title: 'Recursion Basics',
    difficulty: 'Easy',
    topic: ['Recursion'],
  },
  {
    id: 7,
    attempted: true,
    title: 'Hash Tables',
    difficulty: 'Easy',
    topic: ['Data Structures', 'Hashing'],
  },
  {
    id: 8,
    attempted: false,
    title: 'Graph Algorithms',
    difficulty: 'Medium',
    topic: ['Graphs', 'Shortest Path'],
  },
  {
    id: 9,
    attempted: true,
    title: 'Object-Oriented Programming',
    difficulty: 'Medium',
    topic: ['OOP', 'Classes', 'Inheritance'],
  },
  {
    id: 10,
    attempted: false,
    title: 'Concurrency Basics',
    difficulty: 'Hard',
    topic: ['Concurrency', 'Multithreading'],
  },
  {
    id: 11,
    attempted: true,
    title: 'Machine Learning Introduction',
    difficulty: 'Medium',
    topic: ['Machine Learning', 'Algorithms'],
  },
  {
    id: 12,
    attempted: false,
    title: 'Linked Lists',
    difficulty: 'Easy',
    topic: ['Data Structures', 'Linked List'],
  },
  {
    id: 13,
    attempted: true,
    title: 'Binary Trees',
    difficulty: 'Medium',
    topic: ['Trees', 'Binary Tree'],
  },
  {
    id: 14,
    attempted: false,
    title: 'Advanced Recursion',
    difficulty: 'Hard',
    topic: ['Recursion', 'Dynamic Programming'],
  },
  {
    id: 15,
    attempted: true,
    title: 'Greedy Algorithms',
    difficulty: 'Medium',
    topic: ['Algorithms', 'Greedy'],
  },
  {
    id: 16,
    attempted: false,
    title: 'Backtracking',
    difficulty: 'Hard',
    topic: ['Algorithms', 'Backtracking'],
  },
  {
    id: 17,
    attempted: true,
    title: 'Stack and Queues',
    difficulty: 'Easy',
    topic: ['Data Structures', 'Stack', 'Queue'],
  },
  {
    id: 18,
    attempted: false,
    title: 'Graph Theory Basics',
    difficulty: 'Medium',
    topic: ['Graphs', 'Theory'],
  },
  {
    id: 19,
    attempted: true,
    title: 'Advanced Sorting Techniques',
    difficulty: 'Hard',
    topic: ['Algorithms', 'Sorting'],
  },
  {
    id: 20,
    attempted: false,
    title: 'Binary Search',
    difficulty: 'Easy',
    topic: ['Algorithms', 'Search'],
  },
  {
    id: 21,
    attempted: true,
    title: 'KMP String Matching',
    difficulty: 'Hard',
    topic: ['Algorithms', 'String Matching'],
  },
  {
    id: 22,
    attempted: false,
    title: 'Divide and Conquer',
    difficulty: 'Medium',
    topic: ['Algorithms', 'Divide and Conquer'],
  },
  {
    id: 23,
    attempted: true,
    title: 'Trie Data Structure',
    difficulty: 'Hard',
    topic: ['Data Structures', 'Trie'],
  },
  {
    id: 24,
    attempted: false,
    title: 'Heap and Priority Queue',
    difficulty: 'Medium',
    topic: ['Data Structures', 'Heap'],
  },
  {
    id: 25,
    attempted: true,
    title: 'Dynamic Array',
    difficulty: 'Easy',
    topic: ['Arrays', 'Data Structures'],
  },
  {
    id: 26,
    attempted: false,
    title: 'Breadth-First Search',
    difficulty: 'Medium',
    topic: ['Graphs', 'BFS'],
  },
  {
    id: 27,
    attempted: true,
    title: 'Depth-First Search',
    difficulty: 'Medium',
    topic: ['Graphs', 'DFS'],
  },
  {
    id: 28,
    attempted: false,
    title: 'Floyd-Warshall Algorithm',
    difficulty: 'Hard',
    topic: ['Algorithms', 'Graphs'],
  },
  {
    id: 29,
    attempted: true,
    title: 'Binary Indexed Tree',
    difficulty: 'Hard',
    topic: ['Data Structures', 'Fenwick Tree'],
  },
  {
    id: 30,
    attempted: false,
    title: 'Knapsack Problem',
    difficulty: 'Medium',
    topic: ['Algorithms', 'Dynamic Programming'],
  },
  {
    id: 31,
    attempted: true,
    title: 'Segment Tree',
    difficulty: 'Hard',
    topic: ['Data Structures', 'Segment Tree'],
  },
  {
    id: 32,
    attempted: false,
    title: 'Linear Regression',
    difficulty: 'Medium',
    topic: ['Machine Learning', 'Regression'],
  },
  {
    id: 33,
    attempted: true,
    title: 'Polynomial Time Algorithms',
    difficulty: 'Hard',
    topic: ['Algorithms', 'Complexity'],
  },
  {
    id: 34,
    attempted: false,
    title: 'Monte Carlo Simulation',
    difficulty: 'Medium',
    topic: ['Algorithms', 'Simulation'],
  },
  {
    id: 35,
    attempted: true,
    title: 'Neural Networks',
    difficulty: 'Hard',
    topic: ['Machine Learning', 'Neural Networks'],
  },
  {
    id: 36,
    attempted: false,
    title: 'Reinforcement Learning Basics',
    difficulty: 'Hard',
    topic: ['Machine Learning', 'Reinforcement Learning'],
  },
  {
    id: 37,
    attempted: true,
    title: 'Bayesian Networks',
    difficulty: 'Medium',
    topic: ['Machine Learning', 'Bayesian Networks'],
  },
  {
    id: 38,
    attempted: false,
    title: 'Markov Chains',
    difficulty: 'Hard',
    topic: ['Machine Learning', 'Markov Chains'],
  },
  {
    id: 39,
    attempted: true,
    title: 'Quantum Algorithms',
    difficulty: 'Hard',
    topic: ['Algorithms', 'Quantum Computing'],
  },
  {
    id: 40,
    attempted: false,
    title: 'Cryptography Basics',
    difficulty: 'Medium',
    topic: ['Cryptography', 'Security'],
  },
];
