apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
spec:
  selector:
    app: collaboration-service
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: LoadBalancer
