apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: gcr.io/peerprep-438713/chat-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: FRONTEND_URL 
          value: "http://34.101.228.125"