# Build Stage
FROM node:18 AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install 

COPY . .

# Run Stage
FROM node:18-alpine AS run
WORKDIR /app

COPY --from=build /app /app

EXPOSE 3001

CMD ["npm", "run", "dev"]
