steps:
  # Step 1: build and push all images to Artifact Registry

  # Build and push peerprep-fe
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/peerprep-fe:latest",
        "--build-arg",
        "NEXT_PUBLIC_API_GATEWAY_URL=${_NEXT_PUBLIC_API_GATEWAY_URL}",
        "--build-arg",
        "NEXT_PUBLIC_GITHUB_CLIENT_ID=${_NEXT_PUBLIC_GITHUB_CLIENT_ID}",
        "--build-arg",
        "NEXT_PUBLIC_SOCK_SERVER_URL=${_NEXT_PUBLIC_SOCK_SERVER_URL}",
        "--build-arg",
        "NEXT_PUBLIC_AUDIO_SERVER_URL=${_NEXT_PUBLIC_AUDIO_SERVER_URL}",
        "-f",
        "peerprep-fe/Dockerfile",
        "peerprep-fe",
      ]

  # Push the peerprep-fe image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/peerprep-fe:latest",
      ]

  # Step 2: Clean up and deploy to GKE
  - name: "ubuntu"
    args: ["rm", "-rf", "output"]

  # Deploy peerprep-fe to Google Kubernetes Engine (GKE)
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s/peerprep-fe.yml
      - --image=asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/peerprep-fe:latest
      - --location=asia-southeast1
      - --cluster=cs3219-g11-peerprep-kubes

  # Step 3: update the deployments with the new images
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/peerprep-fe"
      - "peerprep-fe=asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/peerprep-fe:latest"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1"
      - "CLOUDSDK_CONTAINER_CLUSTER=cs3219-g11-peerprep-kubes"

substitutions:
  _NEXT_PUBLIC_API_GATEWAY_URL: ""
  _NEXT_PUBLIC_GITHUB_CLIENT_ID: ""
  _NEXT_PUBLIC_SOCK_SERVER_URL: ""
  _NEXT_PUBLIC_AUDIO_SERVER_URL: ""

options:
  dynamic_substitutions: true

images:
  - "asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/peerprep-fe:latest"
