steps:
  # Step 1: build and push all images to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/session-svc:latest",
        "-f",
        "session-service/Dockerfile",
        "session-service",
      ]
    env:
      - "CLOUDSDK_EXPERIMENTAL_DISABLE_HTTP2=true"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/session-svc:latest",
      ]

  # Step 2: Clean up and deploy to GKE
  - name: "ubuntu"
    args: ["rm", "-rf", "output"]

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=k8s/session-service.yml
      - --image=asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/session-svc:latest
      - --location=asia-southeast1
      - --cluster=cs3219-g11-peerprep-kubes

  # Step 3: update the deployments with the new images
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/session-svc"
      - "session-svc=asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/session-svc:latest"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1"
      - "CLOUDSDK_CONTAINER_CLUSTER=cs3219-g11-peerprep-kubes"

images:
  - "asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/session-svc:latest"
