name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install dependencies
        run: pnpm install  
        working-directory: ./project/packages/infra
      - name: Update the resources
        uses: pulumi/actions@v6
        with:
          command: up
          work-dir: ./project/packages/infra
          stack-name: javinchua/lastminprep/lastminprep
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
          USER_SERVICE_SUPABASE_URL: ${{ secrets.USER_SERVICE_SUPABASE_URL}}
          USER_SERVICE_SUPABASE_KEY: ${{ secrets.USER_SERVICE_SUPABASE_KEY }}

          QUESTION_SERVICE_SUPABASE_URL: ${{ secrets.QUESTION_SERVICE_SUPABASE_URL }}
          QUESTION_SERVICE_SUPABASE_KEY: ${{ secrets.QUESTION_SERVICE_SUPABASE_KEY }}

          MATCHING_SERVICE_SUPABASE_URL: ${{ secrets.MATCHING_SERVICE_SUPABASE_URL }}
          MATCHING_SERVICE_SUPABASE_KEY: ${{ secrets.MATCHING_SERVICE_SUPABASE_KEY }}

          COLLABORATION_SERVICE_SUPABASE_URL: ${{ secrets.COLLABORATION_SERVICE_SUPABASE_URL }}
          COLLABORATION_SERVICE_SUPABASE_KEY: ${{ secrets.COLLABORATION_SERVICE_SUPABASE_KEY }}