# This is a basic workflow to help you get started with Actions

name: Actions on Push

# Controls when the workflow will run
on:
  # On push @ branch
  push:
  # When branch is created
  create:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: kimyongbeom/peerprep-actions-runner:latest
      env:
        AGE_SECRET_KEY: ${{ secrets.AGE_SECRET_KEY }}
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      options: --privileged
    concurrency:
      # current branch
      group: ${{ github.ref_name }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/container_setup

      - name: Find Changed Files
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            global_infra:
              - 'tf/**'
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

      - name: Deploy Global Infrastructure
        shell: bash
        if: ${{ github.event_name }} == 'create' || ${{ steps.changes.outputs.global_infra }} == 'true'
        run: cd docker_registry && make deploy
    
      - name: Deploy Backend
        if: ${{ github.event_name }} == 'create' || ${{ steps.changes.outputs.backend }} == 'true'
        shell: bash
        run: cd backend && make deploy
    
      - name: Deploy Frontend
        if: ${{ github.event_name }} == 'create' || ${{ steps.changes.outputs.frontend }} == 'true'
        shell: bash
        run: . $NVM_DIR/nvm.sh && cd frontend && make deploy

